#
# SETUP
#
# 1. Create a service principal in Azure
#
#
# export group=warehouseautomationapi
# export subscription=c9e7aaf4-2cb3-40e0-b1dd-54276cbdfd8b
#
# az ad sp create-for-rbac --name nvmsp1 --role "contributor" --scopes /subscriptions/$subscription/resourceGroups/$grou
#
# 2. Store the credential as a secret called: AZURE_AZ_CREDENTIALS
#
#

name: Rotate keys every month

on:
  workflow_dispatch:
  schedule:
#    - cron: '0 0 1 * *'
    - cron: '*/15 * * * *'

jobs:
  rotate-keys:
   runs-on: ubuntu-latest
    
   steps:
    - name: Checkout this repo
      uses: actions/checkout@v2
      with:
         fetch-depth: 2
         
    - name: Install Azure CLI
      uses: azure/cli@v2
      with:
        azcliversion: latest
        
    - name: Login to Azure
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_AZ_CREDENTIALS }}

    - name: Rotate keys
      run: |
        export group=warehouseautomationapi
        export api=warehouseAutomationAPI
        export fe=nvmwarehouseautomation
        export val=`az functionapp keys set  -n $api -g $group --key-type systemKeys --key-name k1 | jq '.value'| tr -d '"'`
        az webapp config appsettings set  --name $fe -g $group --settings HOSTKEY=$val
